// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Q8u-wZg_rDbuay_tPzIwsnOB0WnbHNI',
    appId: '1:414897252488:web:facb2032f133e63ca4d73d',
    messagingSenderId: '414897252488',
    projectId: 'ride-n-die',
    authDomain: 'ride-n-die.firebaseapp.com',
    storageBucket: 'ride-n-die.appspot.com',
    measurementId: 'G-SGJM14XV81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjutvECs4bkHDOhT1v1lNSesPRajiFgE8',
    appId: '1:414897252488:android:36704d5892c0d0aea4d73d',
    messagingSenderId: '414897252488',
    projectId: 'ride-n-die',
    storageBucket: 'ride-n-die.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDclvgbYF_1azqI7_49hizLLPna_YsLJDY',
    appId: '1:414897252488:ios:653f19a4a8cf9afea4d73d',
    messagingSenderId: '414897252488',
    projectId: 'ride-n-die',
    storageBucket: 'ride-n-die.appspot.com',
    iosBundleId: 'com.example.rideNDie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDclvgbYF_1azqI7_49hizLLPna_YsLJDY',
    appId: '1:414897252488:ios:4e505598632c7276a4d73d',
    messagingSenderId: '414897252488',
    projectId: 'ride-n-die',
    storageBucket: 'ride-n-die.appspot.com',
    iosBundleId: 'com.example.rideNDie.RunnerTests',
  );
}
